'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, Check, Clock3, Info, Search, Sparkles, TriangleAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { serviceSlug } from '@/lib/public-site/service-slug';

export type PublicService = { id: string; name: string; description?: string | null; public_presentation?: string | null; public_benefits?: string[] | null; public_considerations?: string[] | null; public_image_url?: string | null; coming_soon?: boolean; duration_minutes: number; price: number; currency: string; color: string };
const priceLabel = (service: PublicService) => service.coming_soon ? 'Disponível em breve' : Number(service.price) > 0 ? new Intl.NumberFormat('pt-PT', { style: 'currency', currency: service.currency || 'EUR' }).format(Number(service.price)) : 'Sob consulta';

export function PublicServiceExplorer({ services, bookingUrl }: { services: PublicService[]; bookingUrl: string }) {
  const [selected, setSelected] = useState<PublicService | null>(null);
  const [query, setQuery] = useState('');
  const shown = useMemo(() => { const search = query.trim().toLocaleLowerCase('pt-PT'); return search ? services.filter((service) => [service.name, service.description, service.public_presentation].filter(Boolean).join(' ').toLocaleLowerCase('pt-PT').includes(search)) : services; }, [query, services]);
  return <>
    {services.length > 6 && <div className="mt-8 max-w-lg"><label htmlFor="service-search" className="sr-only">Pesquisar serviço</label><div className="relative"><Search className="pointer-events-none absolute top-1/2 left-4 size-4 -translate-y-1/2 text-slate-400" /><input id="service-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Que experiência procura?" className="h-12 w-full rounded-xl border border-slate-200 bg-white pr-4 pl-11 text-sm outline-none transition placeholder:text-slate-400 focus:border-[var(--brand)] focus:ring-2 focus:ring-[var(--brand)]/15" /></div></div>}
    <div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{shown.map((service) => <button type="button" key={service.id} onClick={() => setSelected(service)} className="site-card site-service-card group overflow-hidden rounded-2xl border border-slate-200 text-left transition hover:-translate-y-1 hover:shadow-xl">{service.public_image_url && <img src={service.public_image_url} alt={service.name} className="h-44 w-full object-cover transition duration-500 group-hover:scale-105" />}<div className="p-6"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold tracking-[0.14em] text-[var(--brand)] uppercase">Experiência personalizada</p>{service.coming_soon && <span className="rounded-full bg-amber-100 px-2.5 py-1 text-[10px] font-bold tracking-wide text-amber-800 uppercase">Em breve</span>}</div><h3 className="mt-2 text-xl font-semibold">{service.name}</h3><p className="mt-3 line-clamp-3 min-h-[4.5rem] text-sm leading-6 text-slate-500">{service.description || service.public_presentation || 'Conheça esta modalidade e descubra como a sessão pode ser adaptada às suas necessidades.'}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-sm"><span className="flex items-center gap-1 text-slate-500"><Clock3 className="size-4" />{service.duration_minutes} min</span><span className="font-semibold text-[var(--brand)]">{priceLabel(service)}</span></div><span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-[var(--brand)]">Ver detalhes <ArrowRight className="size-4" /></span></div></button>)}</div>
    {!shown.length && <div className="mt-8 rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Não encontrámos uma modalidade com esse nome. Fale connosco para uma recomendação personalizada.</div>}
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}>{selected && <DialogContent className="max-h-[90vh] overflow-y-auto p-0 sm:max-w-3xl"><div className="grid sm:grid-cols-[.9fr_1.1fr]">{selected.public_image_url ? <img src={selected.public_image_url} alt={selected.name} className="h-56 w-full object-cover sm:h-full" /> : <div className="hidden bg-gradient-to-br from-violet-100 via-white to-emerald-100 sm:flex sm:min-h-96 sm:items-center sm:justify-center"><Sparkles className="size-14 text-[var(--brand)]" /></div>}<div className="p-6 sm:p-8"><DialogHeader><p className="text-sm font-semibold text-[var(--brand)]">{selected.coming_soon ? 'Em breve' : `${selected.duration_minutes} minutos · ${priceLabel(selected)}`}</p><DialogTitle className="text-3xl">{selected.name}</DialogTitle><DialogDescription className="text-base leading-7 text-slate-600">{selected.public_presentation || selected.description || 'Informação desta modalidade em atualização.'}</DialogDescription></DialogHeader><DetailList icon={Check} title="Benefícios" items={selected.public_benefits} tone="emerald" /><DetailList icon={TriangleAlert} title="Cuidados e contraindicações" items={selected.public_considerations} tone="amber" /><a href={`/servicos/${serviceSlug(selected.name)}`} className="mt-6 inline-flex text-sm font-semibold text-[var(--brand)]">Ver página completa</a><div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><Info className="mr-2 inline size-4 text-[var(--brand)]" />{selected.coming_soon ? 'Esta modalidade será disponibilizada em breve. Contacte-nos caso queira receber novidades.' : 'A avaliação é individual. Adaptamos a sessão às suas necessidades e ao seu conforto.'}</div>{!selected.coming_soon && <Button className="mt-5 w-full" render={<a href={`${bookingUrl}${bookingUrl.includes('?') ? '&' : '?'}book=1&service=${encodeURIComponent(selected.id)}`} />}>Marcar esta experiência <ArrowRight /></Button>}</div></div></DialogContent>}</Dialog>
  </>;
}
function DetailList({ icon: Icon, title, items, tone }: { icon: typeof Check; title: string; items?: string[] | null; tone: 'emerald' | 'amber' }) { const entries = items?.filter(Boolean) ?? []; if (!entries.length) return null; return <section className="mt-6"><h4 className="flex items-center gap-2 font-semibold"><span className={tone === 'emerald' ? 'rounded-lg bg-emerald-100 p-1.5 text-emerald-700' : 'rounded-lg bg-amber-100 p-1.5 text-amber-700'}><Icon className="size-4" /></span>{title}</h4><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600">{entries.map((item) => <li key={item} className="flex gap-2"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-slate-400" />{item}</li>)}</ul></section>; }
