const facial = [
['Extensão de pestanas — 1.ª aplicação','35 €'],['Extensão de pestanas — manutenção','25 €'],['Extensão de pestanas — remoção','10 €'],['Brilhante','2 €'],['Lifting de pestanas — aplicação','35 €'],['Pintura de pestanas','8 €'],['Micropigmentação de sobrancelhas — aplicação','180 €'],['Micropigmentação de sobrancelhas — retoque','60 €'],['Limpeza de pele','35 €'],['Threading — sobrancelhas','5 €'],['Threading — buço','5 €'],['Threading — rosto','15 €'],['Henna e design de sobrancelha','10 €']];
const nails = [
['1.ª aplicação S/M','30 €','35 €'],['1.ª aplicação L/XL','35 €','39 €'],['1.ª aplicação XXL','39 €','45 €'],['Manutenção S/M','20 €','29 €'],['Manutenção L/XL','25 €','33 €'],['Manutenção XXL','30 €','38 €'],['Remoção','10 €','12 €']];
const hair = [
['Buço ou queixo','10 €','5 €','—','—'],['Rosto (buço, queixo e bochechas)','20 €','13 €','—','—'],['Axilas','20 €','10 €','25 €','10 €'],['Braços','20 €','5 €','25 €','15 €'],['Mãos','10 €','5 €','15 €','8 €'],['Barriga','20 €','13 €','25 €','15 €'],['Peito','—','—','25 €','12 €'],['Costas','20 €','13 €','25 €','15 €'],['Virilha cavada','15 €','8 €','20 €','—'],['Virilhas completas','20 €','15 €','25 €','—'],['Glúteos','15 €','8 €','20 €','—'],['Meia perna','20 €','13 €','25 €','15 €'],['Perna completa','30 €','20 €','35 €','25 €'],['Corpo completo','55 €','40 €','110 €','65 €']];
function PriceTable({headers,rows}:{headers:string[];rows:string[][]}) {
 return <div className="rp-price-scroll"><table className="rp-price-table"><thead><tr>{headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row[0]}>{row.map((value,i)=>i===0?<th key={i} scope="row">{value}</th>:<td key={i}>{value}</td>)}</tr>)}</tbody></table></div>;
}
export function RpPriceList(){return <section id="precario" className="rp-prices"><p>PREÇÁRIO RP</p><h2>Escolha o seu cuidado.</h2><p>Preçário fornecido pelo Instituto, com entrada em vigor em 01/01/2025. Confirme os valores na marcação.</p>
<h3>Pestanas, sobrancelhas e rosto</h3><PriceTable headers={['Serviço','Preço']} rows={facial}/><p>Manutenções de pestanas a partir de 4 semanas são consideradas 1.ª aplicação. Mega volume: acresce 5 €.</p>
<h3>Unhas</h3><PriceTable headers={['Serviço / tamanho','Gel','Acrílico']} rows={nails}/><p><strong>Gelinho: 16,50 € · Gelinho nos pés: 13 €.</strong></p><p>Manutenção de outra cliente: acresce 5 €. Nail art simples incluída em 2 unhas. Unhas francesas: acresce 3 €. Refazer unha partida: 3 €.</p>
<h3>Depilação a laser e cera</h3><PriceTable headers={['Zona','Mulher · laser','Mulher · cera','Homem · laser','Homem · cera']} rows={hair}/><p>Laser: apresentar-se com a depilação feita, conforme indicação do Instituto. Confirme a preparação na marcação.</p><p>Corpo completo mulher: buço, axilas, virilhas completas e pernas completas. Corpo completo homem: axilas, peito, barriga, costas e pernas completas.</p><p>Gessoterapia, JetBronze e formações/workshops: valores sob consulta.</p><a href="#contacto">Consultar disponibilidade e marcar →</a></section>;}
