import type { AccountRole } from '@/lib/auth/roles';
import type { InteractiveMessagePayload } from '@/lib/whatsapp/interactive';

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from '@/lib/whatsapp/interactive';

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  /** Whether this member is bookable in the clinic agenda. */
  is_professional?: boolean;
  /** Public/internal title shown in agenda resource selectors. */
  professional_title?: string | null;
  /** Colour used when grouping appointments by professional. */
  professional_color?: string | null;
  professional_bio?: string | null;
  professional_phone?: string | null;
  professional_public_slug?: string | null;
  professional_show_online?: boolean;
  commission_executant_percent?: number;
  commission_responsible_percent?: number;
  working_hours?: Record<string, unknown>;
  online_booking_blocked?: boolean;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  /** Public logo/brand mark shown in the CRM chrome. */
  logo_url?: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
  is_professional?: boolean;
  professional_title?: string | null;
  professional_color?: string | null;
  professional_bio?: string | null;
  professional_phone?: string | null;
  professional_public_slug?: string | null;
  professional_show_online?: boolean;
  commission_executant_percent?: number;
  commission_responsible_percent?: number;
  working_hours?: Record<string, unknown>;
  online_booking_blocked?: boolean;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, 'owner'>;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  client_reference?: string | null;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  birth_date?: string | null;
  tax_id?: string | null;
  gender?: 'male' | 'female' | 'non_binary' | 'not_informed' | null;
  address_line?: string | null;
  postal_code?: string | null;
  city?: string | null;
  country?: string | null;
  source?: string | null;
  preferred_contact?: 'whatsapp' | 'phone' | 'email' | null;
  marketing_consent?: boolean;
  marketing_whatsapp_consent?: boolean;
  whatsapp_consent?: boolean;
  privacy_review_status?: 'current' | 'legacy_unverified' | 'withdrawn';
  consent_reviewed_at?: string | null;
  consent_review_source?: string | null;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType =
  | 'conversation_assigned'
  | 'new_message_received'
  | 'conversation_waiting'
  | 'deal_created'
  | 'deal_stage_changed'
  | 'deal_won'
  | 'deal_lost'
  | 'follow_up_due'
  | 'task_due'
  | 'automation_failed'
  | 'flow_handoff'
  | 'flow_failed'
  | 'whatsapp_connected'
  | 'whatsapp_disconnected'
  | 'broadcast_completed'
  | 'broadcast_failed'
  | 'work_time_missing'
  | 'work_time_pause_pending'
  | 'referral_registered'
  | 'referral_qualified'
  | 'referral_reward_issued'
  | 'invoice_requested'
  | 'anamnesis_submitted'
  | 'anamnesis_reviewed'
  | 'appointment_created'
  | 'appointment_rescheduled'
  | 'appointment_cancelled'
  | 'appointment_communication_sent'
  | 'appointment_communication_failed'
  | 'client_created'
  | 'payment_received'
  | 'pack_delivery_sent'
  | 'pack_delivery_failed'
  | 'voucher_delivery_sent'
  | 'voucher_delivery_failed'
  | 'support_ticket_created'
  | 'support_new_message'
  | 'system_alert';

export type NotificationCategory =
  | 'inbox'
  | 'sales'
  | 'finance'
  | 'clinic'
  | 'clients'
  | 'automation'
  | 'system'
  | 'broadcast'
  | 'work_time'
  | 'support';

export type NotificationPriority = 'low' | 'normal' | 'high' | 'critical';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  category?: NotificationCategory | null;
  priority?: NotificationPriority | null;
  action_url?: string | null;
  metadata?: Record<string, unknown> | null;
  resolved_at?: string | null;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus =
  'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

// ============================================================
// Clinic agenda (migration 045)
// ============================================================

export type ClinicAppointmentStatus =
  'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';

export type ClinicAppointmentSource =
  | 'manual'
  | 'public_link'
  | 'client_portal'
  | 'whatsapp'
  | 'automation'
  | 'referral';

export interface ClinicService {
  id: string;
  account_id: string;
  user_id?: string | null;
  name: string;
  reference?: string | null;
  category?: string | null;
  description?: string | null;
  /** Conteúdo apresentado no modal público do site. */
  public_presentation?: string | null;
  public_benefits?: string[] | null;
  public_considerations?: string[] | null;
  public_image_url?: string | null;
  duration_minutes: number;
  price: number;
  currency: string;
  color: string;
  online_enabled?: boolean;
  show_on_site?: boolean;
  internal_booking_enabled?: boolean;
  coming_soon?: boolean;
  iva_enabled?: boolean;
  commissions_enabled?: boolean;
  collaborators_enabled?: boolean;
  personalize_enabled?: boolean;
  details_enabled?: boolean;
  commission_executant_percent?: number;
  commission_responsible_percent?: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface ClinicRoom {
  id: string;
  account_id: string;
  user_id?: string | null;
  name: string;
  description?: string | null;
  color: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface ClinicProduct {
  id: string;
  account_id: string;
  user_id?: string | null;
  name: string;
  description?: string | null;
  sku?: string | null;
  price: number;
  currency: string;
  stock_quantity: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export type FinanceSaleStatus =
  'open' | 'partially_paid' | 'paid' | 'voided' | 'refunded';
export type FinancePaymentMethod =
  | 'cash'
  | 'card'
  | 'mb_way'
  | 'multibanco'
  | 'bank_transfer'
  | 'voucher'
  | 'client_credit'
  | 'other';
export type FinanceItemType =
  'service' | 'product' | 'pack' | 'voucher' | 'custom';

export interface FinanceCashSession {
  id: string;
  account_id: string;
  opened_by_user_id?: string | null;
  closed_by_user_id?: string | null;
  status: 'open' | 'closed';
  opening_amount: number;
  closing_counted_amount?: number | null;
  expected_amount?: number | null;
  difference_amount?: number | null;
  expected_breakdown?: Record<string, number>;
  closing_breakdown?: Record<string, number>;
  reconciliation_breakdown?: Record<
    string,
    { expected: number; counted: number; difference: number }
  >;
  notes?: string | null;
  opened_at: string;
  closed_at?: string | null;
  created_at: string;
}

export interface FinanceCashMovement {
  id: string;
  account_id: string;
  cash_session_id: string;
  movement_type:
    'deposit' | 'withdrawal' | 'expense' | 'refund' | 'adjustment' | 'tip';
  payment_method?: FinancePaymentMethod;
  category?: string | null;
  amount: number;
  description: string;
  reference?: string | null;
  sale_id?: string | null;
  payment_id?: string | null;
  created_by_user_id?: string | null;
  created_at: string;
}

export interface FinanceCashSnapshot {
  opening_amount: number;
  cash_received: number;
  deposits: number;
  outflows: number;
  expected_amount: number;
  payments_by_method?: Partial<Record<FinancePaymentMethod, number>>;
  tips_by_method?: Partial<Record<FinancePaymentMethod, number>>;
}

export interface FinanceFundAccount {
  id: string;
  name: string;
  account_type: 'cash' | 'bank' | 'other';
  institution?: string | null;
  currency: string;
  is_active: boolean;
  balance: number;
}

export interface FinancePackCatalog {
  id: string;
  account_id: string;
  created_by_user_id?: string | null;
  name: string;
  description?: string | null;
  reference?: string | null;
  price: number;
  currency: string;
  validity_days: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  items?: FinancePackItem[];
}

export interface FinancePackItem {
  id: string;
  pack_id: string;
  service_id: string;
  sessions: number;
  service?: ClinicService | null;
}

export interface FinanceSale {
  id: string;
  sale_number: number;
  account_id: string;
  contact_id?: string | null;
  appointment_id?: string | null;
  cash_session_id?: string | null;
  created_by_user_id?: string | null;
  status: FinanceSaleStatus;
  currency: string;
  subtotal: number;
  discount_amount: number;
  tax_amount: number;
  total_amount: number;
  paid_amount: number;
  balance_due: number;
  /** A sale recorded for audit after it was paid outside this CRM. */
  is_historical?: boolean;
  notes?: string | null;
  completed_at?: string | null;
  voided_at?: string | null;
  refunded_at?: string | null;
  void_reason?: string | null;
  refund_reason?: string | null;
  reversed_by_user_id?: string | null;
  created_at: string;
  updated_at: string;
  contact?: Contact | null;
  items?: FinanceSaleItem[];
  payments?: FinancePayment[];
  invoice_request?: FinanceInvoiceRequest | null;
}

export interface FinanceInvoiceRequest {
  id: string;
  account_id: string;
  sale_id: string;
  contact_id: string;
  requested_by_auth_user_id?: string | null;
  status: 'pending' | 'processing' | 'issued' | 'rejected' | 'cancelled';
  fiscal_name: string;
  tax_id: string;
  email: string;
  address_line?: string | null;
  postal_code?: string | null;
  city?: string | null;
  country: string;
  client_notes?: string | null;
  invoice_number?: string | null;
  invoice_document_url?: string | null;
  invoice_document_path?: string | null;
  invoice_file_name?: string | null;
  invoice_file_size?: number | null;
  invoice_uploaded_at?: string | null;
  fiscal_provider?: string | null;
  fiscal_document_id?: string | null;
  fiscal_document_type?: string | null;
  fiscal_status?:
    'not_sent' | 'queued' | 'sent' | 'issued' | 'failed' | 'cancelled';
  fiscal_error?: string | null;
  fiscal_payload?: Record<string, unknown> | null;
  fiscal_sent_at?: string | null;
  fiscal_issued_at?: string | null;
  admin_notes?: string | null;
  handled_by_user_id?: string | null;
  requested_at: string;
  processing_at?: string | null;
  completed_at?: string | null;
  updated_at: string;
  sale?: FinanceSale | null;
  contact?: Contact | null;
}

export interface FinanceSaleItem {
  id: string;
  sale_id: string;
  account_id: string;
  item_type: FinanceItemType;
  source_id?: string | null;
  name_snapshot: string;
  reference_snapshot?: string | null;
  quantity: number;
  unit_price: number;
  discount_amount: number;
  tax_rate: number;
  tax_amount: number;
  line_total: number;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface FinancePayment {
  id: string;
  account_id: string;
  sale_id: string;
  cash_session_id?: string | null;
  received_by_user_id?: string | null;
  method: FinancePaymentMethod;
  status: 'pending' | 'confirmed' | 'voided' | 'refunded';
  amount: number;
  reference_code?: string | null;
  notes?: string | null;
  paid_at: string;
  created_at: string;
}

export interface FinanceVoucher {
  id: string;
  account_id: string;
  issued_sale_id?: string | null;
  owner_contact_id?: string | null;
  code: string;
  initial_balance: number;
  current_balance: number;
  currency: string;
  status: 'pending' | 'active' | 'used' | 'expired' | 'cancelled';
  recipient_name?: string | null;
  message?: string | null;
  voucher_type?: 'gift_card' | 'service';
  service_id?: string | null;
  service?: ClinicService | null;
  pin_code?: string | null;
  remaining_uses?: number | null;
  expires_at?: string | null;
  created_at: string;
  updated_at: string;
  owner?: Contact | null;
}

export interface FinanceVoucherTransferRequest {
  id: string;
  account_id: string;
  voucher_id: string;
  recipient_name: string;
  recipient_phone: string;
  status: 'pending' | 'contacted' | 'approved' | 'rejected' | 'cancelled';
  reviewed_by_user_id?: string | null;
  reviewed_at?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  voucher?: FinanceVoucher | null;
}

export interface FinanceClientWallet {
  id: string;
  account_id: string;
  contact_id: string;
  currency: string;
  balance: number;
  created_at: string;
  updated_at: string;
}

export interface FinanceWalletTransaction {
  id: string;
  account_id: string;
  wallet_id: string;
  transaction_type: 'credit' | 'debit' | 'refund' | 'adjustment';
  amount: number;
  balance_after: number;
  referral_reward_id?: string | null;
  sale_id?: string | null;
  payment_id?: string | null;
  performed_by_user_id?: string | null;
  description?: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface FinanceBenefitLog {
  id: string;
  account_id: string;
  voucher_id?: string | null;
  client_pack_id?: string | null;
  appointment_id?: string | null;
  action:
    'issued' | 'reserved' | 'used' | 'released' | 'cancelled' | 'adjusted';
  amount: number;
  sessions: number;
  performed_by_user_id?: string | null;
  performed_by_name?: string | null;
  approved_by_user_id?: string | null;
  approved_by_name?: string | null;
  notes?: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  appointment?: {
    id?: string | null;
    scheduled_start?: string | null;
    service?: { name?: string | null } | null;
    contact?: { name?: string | null; phone?: string | null } | null;
  } | null;
}

export interface FinanceClientPack {
  id: string;
  account_id: string;
  contact_id: string;
  pack_id: string;
  sale_id?: string | null;
  status: 'pending' | 'active' | 'consumed' | 'expired' | 'cancelled';
  purchased_at: string;
  expires_at?: string | null;
  code?: string | null;
  pin_code?: string | null;
  contact?: Contact | null;
  pack?: FinancePackCatalog | null;
  balances?: FinanceClientPackBalance[];
}

export interface FinanceClientPackBalance {
  id: string;
  client_pack_id: string;
  service_id: string;
  total_sessions: number;
  used_sessions: number;
  remaining_sessions: number;
  service?: ClinicService | null;
}

export interface FinanceAppointmentBenefit {
  id: string;
  account_id: string;
  appointment_id: string;
  contact_id: string;
  benefit_type: 'voucher' | 'pack';
  voucher_id?: string | null;
  client_pack_id?: string | null;
  client_pack_balance_id?: string | null;
  service_id?: string | null;
  reserved_amount: number;
  reserved_sessions: number;
  status: 'reserved' | 'consumed' | 'released';
  reserved_at: string;
  consumed_at?: string | null;
  released_at?: string | null;
  created_at: string;
  updated_at: string;
  voucher?: FinanceVoucher | null;
  client_pack?: FinanceClientPack | null;
}

export interface ClinicAppointment {
  id: string;
  account_id: string;
  user_id?: string | null;
  contact_id?: string | null;
  service_id?: string | null;
  professional_profile_id?: string | null;
  room_id?: string | null;
  scheduled_start: string;
  scheduled_end: string;
  status: ClinicAppointmentStatus;
  source: ClinicAppointmentSource;
  price: number;
  original_price?: number | null;
  manual_discount_amount?: number | null;
  manual_discount_reason?: string | null;
  referral_id?: string | null;
  referral_discount_type?: 'fixed_credit' | 'percentage' | 'service' | null;
  referral_discount_value?: number | null;
  referral_discount_amount?: number;
  currency: string;
  notes?: string | null;
  coupon_code?: string | null;
  treatment_notes?: string | null;
  confirmation_sent_at?: string | null;
  confirmation_status?: 'not_required' | 'pending' | 'confirmed' | 'declined';
  confirmation_requested_at?: string | null;
  confirmation_response_at?: string | null;
  confirmation_request_message?: string | null;
  reminder_sent_at?: string | null;
  confirmation_reminder_sent_at?: string | null;
  anamnesis_form_id?: string | null;
  original_scheduled_start?: string | null;
  original_scheduled_end?: string | null;
  schedule_change_count?: number;
  reschedule_count?: number;
  last_schedule_change_at?: string | null;
  last_schedule_change_type?: string | null;
  last_reschedule_reason?: string | null;
  arrived_at?: string | null;
  paid_at?: string | null;
  cancelled_at?: string | null;
  created_at: string;
  updated_at: string;
  contact?: Contact | null;
  service?: ClinicService | null;
  room?: ClinicRoom | null;
  professional?: Profile | null;
}

export interface ClinicTimeBlock {
  id: string;
  account_id: string;
  user_id?: string | null;
  professional_profile_id?: string | null;
  room_id?: string | null;
  starts_at: string;
  ends_at: string;
  reason?: string | null;
  is_online_block: boolean;
  external_calendar_feed_id?: string | null;
  external_uid?: string | null;
  created_at: string;
  updated_at: string;
  room?: ClinicRoom | null;
  professional?: Profile | null;
}

export type ClinicAgendaEntityType = 'appointment' | 'time_block';
export type ClinicAgendaEventAction =
  | 'created'
  | 'updated'
  | 'deleted'
  | 'rescheduled'
  | 'schedule_changed'
  | 'wrong_booking_moved'
  | 'status_changed'
  | 'message_sent';

export interface ClinicAgendaEvent {
  id: string;
  account_id: string;
  user_id?: string | null;
  entity_type: ClinicAgendaEntityType;
  entity_id: string;
  action: ClinicAgendaEventAction;
  reason?: string | null;
  metadata: Record<string, unknown>;
  old_starts_at?: string | null;
  old_ends_at?: string | null;
  new_starts_at?: string | null;
  new_ends_at?: string | null;
  created_at: string;
}

export type BroadcastStatus =
  'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus =
  'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  'contact_field' | 'tag_presence' | 'message_content' | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}
