-- Individual clinical anamnesis definitions for every service modality.
-- Keeps account-level custom questions while replacing the old grouped list.

UPDATE clinic_communication_settings
SET anamnesis_form_config = jsonb_build_object(
  'modalities',
  '[
    {"id":"tantric_sensitive","label":"Massagem Tântrica/Sensitiva","enabled":true,"aliases":["tântrica/sensitiva","tantrica/sensitiva"],"questions":[{"id":"tantric_sensitive_first","label":"É a sua primeira experiência nesta modalidade?","type":"yes_no","required":true},{"id":"tantric_sensitive_boundaries","label":"Indique limites, zonas que não autoriza tocar e preferências de conforto.","type":"textarea","required":true},{"id":"tantric_sensitive_skin","label":"Possui irritação, infeção, lesão cutânea ou sensibilidade a óleos?","type":"yes_no","required":false}]},
    {"id":"relaxing","label":"Massagem Relaxante","enabled":true,"aliases":["relaxante"],"questions":[{"id":"relaxing_pressure","label":"Que pressão prefere: suave, média ou intensa?","type":"textarea","required":false},{"id":"relaxing_avoid","label":"Existem zonas dolorosas, sensíveis ou que devem ser evitadas?","type":"textarea","required":false}]},
    {"id":"therapeutic","label":"Massagem Terapêutica","enabled":true,"aliases":["terapêutica","terapeutica"],"questions":[{"id":"therapeutic_pain","label":"Localize a dor, indique a intensidade de 0 a 10 e há quanto tempo começou.","type":"textarea","required":true},{"id":"therapeutic_diagnosis","label":"Possui diagnóstico, exames, cirurgia recente ou recomendação médica?","type":"textarea","required":false},{"id":"therapeutic_mobility","label":"Que movimentos ou atividades estão limitados?","type":"textarea","required":false}]},
    {"id":"sports","label":"Massagem Desportiva","enabled":true,"aliases":["desportiva"],"questions":[{"id":"sports_activity","label":"Qual desporto pratica, com que frequência e qual o objetivo da sessão?","type":"textarea","required":true},{"id":"sports_injury","label":"Possui lesão atual, dor aguda, edema ou está em recuperação?","type":"textarea","required":false},{"id":"sports_event","label":"Tem treino ou competição nas próximas 48 horas?","type":"yes_no","required":false}]},
    {"id":"hot_stones","label":"Massagem Pedras Quentes","enabled":true,"aliases":["pedras quentes"],"questions":[{"id":"stones_heat","label":"Possui sensibilidade reduzida ou intolerância ao calor?","type":"yes_no","required":true},{"id":"stones_circulation","label":"Possui diabetes, varizes, trombose ou problemas circulatórios?","type":"yes_no","required":false},{"id":"stones_skin","label":"Indique inflamações, lesões cutâneas ou zonas onde não deve ser aplicado calor.","type":"textarea","required":false}]},
    {"id":"hot_candles","label":"Massagem Velas Quentes","enabled":true,"aliases":["velas quentes"],"questions":[{"id":"candles_allergy","label":"Possui alergia a cosméticos, fragrâncias, ceras ou óleos?","type":"yes_no","required":true},{"id":"candles_heat","label":"Possui sensibilidade reduzida ou intolerância ao calor?","type":"yes_no","required":false},{"id":"candles_skin","label":"Indique dermatites, feridas, irritações ou tratamentos de pele recentes.","type":"textarea","required":false}]},
    {"id":"cupping","label":"Ventosaterapia","enabled":true,"aliases":["ventosaterapia","ventosa"],"questions":[{"id":"cupping_anticoagulant","label":"Utiliza anticoagulantes ou apresenta hematomas com facilidade?","type":"yes_no","required":true},{"id":"cupping_skin","label":"Possui feridas, varizes salientes, infeções ou inflamação na zona a tratar?","type":"yes_no","required":false},{"id":"cupping_marks","label":"Compreende e aceita que a técnica pode deixar marcas temporárias?","type":"yes_no","required":true}]},
    {"id":"reflexology","label":"Reflexologia Podal","enabled":true,"aliases":["reflexologia podal","reflexologia"],"questions":[{"id":"reflexology_feet","label":"Possui feridas, infeção, micose, fratura ou cirurgia recente nos pés?","type":"yes_no","required":true},{"id":"reflexology_neuropathy","label":"Possui diabetes, neuropatia ou perda de sensibilidade nos pés?","type":"yes_no","required":false},{"id":"reflexology_pregnancy","label":"Está grávida ou existe possibilidade de gravidez?","type":"yes_no","required":false}]},
    {"id":"myofascial","label":"Liberação Miofascial","enabled":true,"aliases":["liberação miofascial","liberacao miofascial","miofascial"],"questions":[{"id":"myofascial_restriction","label":"Indique a zona de restrição, dor e movimentos limitados.","type":"textarea","required":true},{"id":"myofascial_injury","label":"Possui lesão aguda, fratura, cirurgia recente ou doença do tecido conjuntivo?","type":"yes_no","required":false},{"id":"myofascial_treatment","label":"Realiza fisioterapia ou outro acompanhamento para esta condição?","type":"textarea","required":false}]},
    {"id":"tantric","label":"Massagem Tântrica","enabled":true,"aliases":["massagem tântrica","massagem tantrica"],"questions":[{"id":"tantric_first","label":"É a sua primeira experiência nesta modalidade?","type":"yes_no","required":true},{"id":"tantric_boundaries","label":"Indique claramente os seus limites, zonas excluídas e preferências.","type":"textarea","required":true},{"id":"tantric_consent","label":"Compreende que pode interromper ou ajustar a sessão a qualquer momento?","type":"yes_no","required":true}]},
    {"id":"sensitive","label":"Massagem Sensitiva","enabled":true,"aliases":["massagem sensitiva"],"questions":[{"id":"sensitive_boundaries","label":"Indique limites de toque, zonas excluídas e sensibilidades.","type":"textarea","required":true},{"id":"sensitive_goal","label":"O que procura nesta sessão e o que ajuda a sentir-se confortável?","type":"textarea","required":false},{"id":"sensitive_oils","label":"Possui alergia ou sensibilidade a óleos e fragrâncias?","type":"yes_no","required":false}]},
    {"id":"lomi_lomi","label":"Massagem Lomi-Lomi","enabled":true,"aliases":["lomi-lomi","lomi lomi"],"questions":[{"id":"lomi_oils","label":"Possui alergia ou sensibilidade a óleos e fragrâncias?","type":"yes_no","required":false},{"id":"lomi_pressure","label":"Indique a pressão preferida e zonas que devem ser evitadas.","type":"textarea","required":false},{"id":"lomi_mobility","label":"Possui limitação de mobilidade, cirurgia ou lesão recente?","type":"yes_no","required":false}]},
    {"id":"nuru","label":"Massagem Nuru","enabled":true,"aliases":["massagem nuru","nuru"],"questions":[{"id":"nuru_skin","label":"Possui alergias, dermatite, feridas ou sensibilidade cutânea?","type":"yes_no","required":true},{"id":"nuru_boundaries","label":"Indique limites, zonas excluídas e qualquer adaptação necessária.","type":"textarea","required":true},{"id":"nuru_consent","label":"Compreende que pode interromper ou ajustar a sessão a qualquer momento?","type":"yes_no","required":true}]},
    {"id":"slimming","label":"Massagem Redutora de Medidas","enabled":true,"aliases":["redutora de medidas","redutora"],"questions":[{"id":"slimming_goal","label":"Quais zonas pretende trabalhar e qual o seu objetivo?","type":"textarea","required":false},{"id":"slimming_circulation","label":"Possui varizes, trombose, fragilidade capilar ou problemas circulatórios?","type":"yes_no","required":true},{"id":"slimming_surgery","label":"Fez cirurgia, procedimento estético ou teve parto recentemente?","type":"yes_no","required":false}]},
    {"id":"modeling","label":"Massagem Modeladora","enabled":true,"aliases":["modeladora"],"questions":[{"id":"modeling_goal","label":"Quais zonas pretende trabalhar e qual o resultado esperado?","type":"textarea","required":false},{"id":"modeling_circulation","label":"Possui varizes, trombose, hematomas frequentes ou problemas circulatórios?","type":"yes_no","required":true},{"id":"modeling_skin","label":"Possui inflamação, dor aguda, lesão de pele ou cirurgia recente?","type":"yes_no","required":false}]}
  ]'::JSONB,
  'customQuestions', COALESCE(anamnesis_form_config->'customQuestions', '[]'::JSONB)
);

NOTIFY pgrst, 'reload schema';
