export type SitePlan = {
  name: string;
  price: string;
  description: string;
  features: string[];
  highlighted?: boolean;
};
export type SiteBenefit = { title: string; description: string };
export type SiteTestimonial = { name: string; role: string; quote: string };
export type SiteFaq = { question: string; answer: string };
export type PublicSiteSettings = {
  account_id: string;
  slug: string;
  enabled: boolean;
  site_theme: import('./themes').PublicSiteThemeId;
  primary_color: string;
  accent_color: string;
  hero_badge: string | null;
  hero_title: string;
  hero_subtitle: string | null;
  hero_image_url: string | null;
  about_title: string;
  about_text: string | null;
  history_text: string | null;
  mission_text: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  whatsapp_phone: string | null;
  address: string | null;
  opening_hours: string | null;
  instagram_url: string | null;
  facebook_url: string | null;
  linkedin_url: string | null;
  show_services: boolean;
  show_team: boolean;
  show_plans: boolean;
  show_benefits: boolean;
  show_testimonials: boolean;
  google_reviews_enabled: boolean;
  google_place_id: string | null;
  google_review_url: string | null;
  show_faq: boolean;
  show_booking: boolean;
  plans: SitePlan[];
  benefits: SiteBenefit[];
  testimonials: SiteTestimonial[];
  faqs: SiteFaq[];
  seo_title: string | null;
  seo_description: string | null;
};
